name: Build and Push

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  push-image-to-container:
    name: Build and Push the React App Docker Image
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    
    defaults:
      run:
        working-directory: ./pocs/application/tt-simple-reactapp

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ env.ARM_CLIENT_ID }}
            tenant-id: ${{ env.ARM_TENANT_ID }}
            subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - uses: azure/docker-login@v1
        with:
          login-server: contoso.azurecr.io
          username: ${{ secrets.TF_VAR_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.TF_VAR_DOCKER_REGISTRY_PASSWORD }}

      - run: |
          docker build -t tt-react-app .
          docker tag tt-react-app swttpoc1acr001.azurecr.io/tt-react-app:0.0.1
          docker push swttpoc1acr001.azurecr.io/tt-react-app:0.0.1
