name: Provision Azure Storage Account

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read
  issues: write

jobs:

  terraform-ci:
    name: Terraform CI
    uses: ./.github/workflows/terraform-ci.yml
    with:
      working-directory: ./pocs/infrastructure/terraform/setup

  terraform-setup-cd:
      needs: terraform-ci
      name: Terraform Provision Azure Storage Account
      runs-on: ubuntu-latest
  
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        
      defaults:
        run:
          working-directory: ./pocs/infrastructure/terraform/setup
          
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
  
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.9.1
  
        - name: 'Az CLI login'
          uses: azure/login@v1
          with:
              client-id: ${{ env.ARM_CLIENT_ID }}
              tenant-id: ${{ env.ARM_TENANT_ID }}
              subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
  
        - name: Terraform Init
          run: |
            terraform init
  
        - name: Terraform Plan
          run: |
            terraform plan -var-file="variables.tfvars" -out state.tfplan
  
        - name: Approve Terraform Apply
          uses: trstringer/manual-approval@v1
          with:
            secret: ${{ github.TOKEN }}
            approvers: alejo-maya
            minimum-approvals: 1
            issue-title: "Deploying infra for the setup to an azure Storage Account"
            issue-body: "Please approve or deny the deployment."
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: 'approve'
            additional-denied-words: 'reject'
  
        - name: Terraform Apply
          run: |
            terraform apply "state.tfplan"

        - name: Upload tfstate
          uses: actions/upload-artifact@v4
          with:
            name: tfstate-artifact
            path: ./pocs/infrastructure/terraform/setup/terraform.tfstate

  migrate-setup-state-to-azure:
    name: Migrate Setup State To Azure
    runs-on: ubuntu-latest
    needs: terraform-setup-cd
    
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}       

    defaults:
      run:
        working-directory: ./pocs/infrastructure/terraform/setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.1

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

    - name: Download tfstate
      uses: actions/download-artifact@v4
      with:
        name: tfstate-artifact
        path: ./pocs/infrastructure/terraform/setup

    - name: Upload state
      run: |
        chmod +x upload_blob.sh
        ./upload_blob.sh

  delete:
    name: Delete Artifact
    needs: migrate-setup-state-to-azure
    runs-on: ubuntu-latest

    steps:
    - name: Delete artifact
      uses: geekyeggo/delete-artifact@v5
      with:
          name: tfstate-artifact
  
