name: RHR Build and Push React App Image

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  push-image-to-container:
    name: Build and Push the React App Docker Image
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ACR_USERNAME: swttpocrhracr001
      DOCKER_IMAGE_NAME: tt-react-app
      ACR_IMAGE_URL: swttpocrhracr001.azurecr.io/tt-react-app:0.0.1
    
    defaults:
      run:
        working-directory: ./pocs/application/tt-simple-reactapp

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ env.ARM_CLIENT_ID }}
            tenant-id: ${{ env.ARM_TENANT_ID }}
            subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Azure Container Registry Login
        run: az acr login --name ${{ env.ACR_USERNAME }}

      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Tag Docker Image
        run: docker tag ${{ env.DOCKER_IMAGE_NAME }} ${{ env.ACR_IMAGE_URL }} 

      - name: Push Docker Image
        run: docker push ${{ env.ACR_IMAGE_URL }}
