name: Provision Azure Container Registry

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read
  issues: write

jobs:

  terraform-ci:
    name: Terraform CI
    uses: ./.github/workflows/terraform-ci.yml
    with:
      working-directory: ./pocs/infrastructure/terraform/container-registry

      
  terraform-acr-cd:
    needs: terraform-ci
    name: Terraform Provision Azure Container Registry
    runs-on: ubuntu-latest
      
    defaults:
      run:
        working-directory: ./pocs/infrastructure/terraform/container-registry
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.ARM_CLIENT_ID }}
            tenant-id: ${{ secrets.ARM_TENANT_ID }}
            subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          terraform init -backend-config="state.backend.conf" -reconfigure

      - name: Terraform Plan
        run: |
          terraform plan -var-file="variables.tfvars" -out container-registry.tfplan

      - name: Approve Terraform Apply
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: alejo-maya
          minimum-approvals: 1
          issue-title: "Deploying infra for the webapp to an azure web server"
          issue-body: "Please approve or deny the deployment."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: 'approve'
          additional-denied-words: 'reject'

      - name: Terraform Apply
        run: |
          terraform apply "container-registry.tfplan"


  build-push-react-image:
    name: Build and Push React App Image Step
    needs: terraform-acr-cd
    uses: ./.github/workflows/rhr-docker-buildpush.yml
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}  
      
