name: Terraform CI

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  terraform-ci:
    name: Terraform Validate and Format
    runs-on: ubuntu-latest

    # Save all directories containing terraform files in a variable
    env:
      tfDIRS: $(find . -name '*.tf' -exec dirname {} \; | sort -u)

    steps:

      - run: find . -name '*.tf' -exec dirname {} \; | sort -u 

      # Display the event that triggered the workflow
      - run: echo "The job was triggered by a ${{ github.event_name }} event."

       # Information about the repository and branch
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      - name: Terraform Format Check
        run: |
          for dir in $tfDIRS; do
            echo "Running terraform fmt  in directory: $dir"
            (cd "$dir" && terraform fmt)
          done

      - name: Terraform Validate
        run: |
          for dir in $tfDIRS; do
            echo "Running terraform validate in directory: $dir"
            (cd "$dir" && terraform validate)
          done
