name: Terraform CI

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**/*.tf'
  workflow_dispatch:

# Check if the head branch starts with 'feature/'
jobs:
  check-branch:
    name: Check branch name
    runs-on: ubuntu-latest

    steps:
      - run: |
          if [[ ! "${{ github.head_ref }}" =~ ^feature ]]; then
            echo "This workflow only runs for branches starting with 'feature/'."
            exit 1
          fi


  terraform-ci:
    name: Terraform Validate and Format
    needs: check-branch
    runs-on: ubuntu-latest

    steps:

      # Display the event that triggered the workflow
      - run: echo "The job was triggered by a ${{ github.event_name }} event."

       # Information about the repository and branch
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

       # Save all directories containing terraform files in a variable
      - name: Find Directories
        id: find_dirs
        run: |
          tfDIRS=$(find . -name '*.tf' -exec dirname {} \; | sort -u)
          for dir in $tfDIRS; do
            echo "Found Terraform files in directory: $dir"
          done
          {
            echo 'tfDIRS<<EOF'
            echo "$tfDIRS"
            echo EOF
          } >> "$GITHUB_ENV"

      # Terraform initialization ignoring backend.tf
      - name: Terraform Init
        run: |
          tfDIRS="${{ env.tfDIRS }}"
          for dir in $tfDIRS; do
            (cd "$dir" &&
            echo "Initializing Terraform in directory: $dir" &&
            terraform init -backend=false)
          done

      - name: Terraform Format Check
        run: |
          tfDIRS="${{ env.tfDIRS }}"
          for dir in $tfDIRS; do
            echo "Running terraform fmt in directory: $dir"
            (cd "$dir" && terraform fmt --check)
          done

      - name: Terraform Validate
        run: |
          tfDIRS="${{ env.tfDIRS }}"
          for dir in $tfDIRS; do
            echo "Running terraform validate in directory: $dir"
            (cd "$dir" && terraform validate)
          done
