name: Test Input Integration

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  job-test-1:
    runs-on: ubuntu-latest
    name: Job-Test-1

    steps:
      - run: echo aloja


  job-test-2:
    name: Call User Input Workflow
    needs: job-test-1
    uses: ./.github/workflows/input-test.yml
    with:
      varfile_path: pocs/infrastructure/terraform/webapp

  job-test-3:
    runs-on: ubuntu-latest
    name: job-test-3
    needs: job-test-2
    steps:
      # - name: Get Output from User Input Workflow
      #   id: get-output
      #   run: |
      #     echo "Fetching outputs from previous workflow run"
      #     echo "::set-output name=var_file::$(jq -r '.jobs.test.outputs.var_file' ${{ steps.call-input-workflow.outputs.workflow_outputs }})"

      # - name: Use Var File
      #   run: echo "${{ steps.get-output.outputs.var_file }}"
      - run: echo ${{ needs.job-test-2.outputs.varfile }}
