name: Test Input Integration

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  issues: write

jobs:
  job-test-1:
    runs-on: ubuntu-latest
    name: Job-Test-1

    steps:
      - run: echo aloja


  job-test-2:
    name: Call User Input Workflow
    needs: job-test-1
    uses: ./.github/workflows/input-test.yml
    with:
      varfile_path: pocs/infrastructure/terraform/webapp

  job-test-3:
    runs-on: ubuntu-latest
    name: job-test-3
    needs: job-test-2
    steps:
      - run: echo ${{ needs.job-test-2.outputs.varfile }}
