name: Test Input Integration

on:
  workflow_dispatch:

jobs:
  job-test-1:
    runs-on: ubuntu-latest
    name: Job-Test-1

    steps:
      - run: echo aloja

      - name: Call User Input Workflow
        id: call-input-workflow
        uses: ./.github/workflows/input-test.yml
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          varfile_path: pocs/infrastructure/terraform/webapp

      - name: Get Output from User Input Workflow
        id: get-output
        run: |
          echo "Fetching outputs from previous workflow run"
          echo "::set-output name=var_file::$(jq -r '.jobs.test.outputs.var_file' ${{ steps.call-input-workflow.outputs.workflow_outputs }})"

      - name: Use Var File
        run: echo "${{ steps.get-output.outputs.var_file }}"
