name: Provision Azure Web Server

on:
#   push:
#     branches:
#       - main
#       - develop
#     paths:
#       - 'pocs/infrastructure/terraform/webapp/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      
    # defaults:
    #   run:
    #     working-directory: pocs/infrastructure/terraform/webapp

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ env.ARM_CLIENT_ID }}
            tenant-id: ${{ env.ARM_TENANT_ID }}
            subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
  
      - name: 'Run Azure CLI commands'
        run: |
            az account show
            pwd 

      - name: Terraform Init
        run: |
          cd pocs/infrastructure/terraform/webapp
          terraform init -backend-config="state.backend.conf" -reconfigure

      - name: Terraform Plan
        run: |
          cd pocs/infrastructure/terraform/webapp
          terraform plan -var-file="variables.tfvars" -out webapp.tfplan

  terraform-apply:
    name: Approve Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: test-tech-titans-gha
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: 'approve'
          additional-denied-words: 'reject'
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      - name: Terraform Apply
        run: |
          cd pocs/infrastructure/terraform/webapp
          terraform apply "webapp.tfplan"

    # steps:
    #  - name: Wait for approval
    #    uses: trstringer/manual-approval@v1
    #    with:    
    #      secret: "yes"
    #      approvers: alejo-maya
    #      minimum-approvals: 1

          
      # - name: Manual approval required
      #   id: approval
      #   run: |
      #     echo "To proceed with applying Terraform changes, approve this workflow run."
      #     echo "Approval can be given by navigating to the Actions tab above."

  # terraform-apply:
  #   name: Terraform Apply
  #   runs-on: ubuntu-latest
  #   # if: success() && github.event_name == 'workflow_dispatch'
  #   needs: approve-apply

