name: Provision Azure Web Server

on:
#   push:
#     branches:
#       - main
#       - develop
#     paths:
#       - 'pocs/infrastructure/terraform/webapp/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: pocs/infrastructure/terraform/webapp

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      # - name: 'Run Azure CLI commands'
      #   run: |
      #       az account show
      #       pwd 

      - name: Terraform Init
        run: |
          cd pocs/infrastructure/terraform/webapp
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p=${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account show
          pwd
          terraform init -backend-config="state.backend.conf" -reconfigure

      - name: Terraform Plan
        run: |
          terraform plan -var-file="variables.tfvars" -out webapp.tfplan

  approve-apply:
    name: Approve Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Manual approval required
        id: approval
        run: |
          echo "To proceed with applying Terraform changes, approve this workflow run."
          echo "Approval can be given by navigating to the Actions tab above."

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: success() && github.event_name == 'workflow_dispatch'
    needs: terraform-plan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      - name: Terraform Apply
        run: |
          terraform apply "webapp.tfplan" -auto-approve
