name: Provision Azure Web Server

on:
#   push:
#     branches:
#       - main
#       - develop
#     paths:
#       - 'pocs/infrastructure/terraform/webapp/**'
  workflow_dispatch:

env:
  WEBAPP_DIRECTORY: ./pocs/infrastructure/terraform/webapp

permissions:
  id-token: write
  contents: read
  issues: write

jobs:

  terraform-ci:
    name: Terraform CI
    uses: ./.github/workflows/terraform-ci.yml
    with:
      working-directory: ${{ env.WEBAPP_DIRECTORY }}

  terraform-cd:
    name: Terraform Provision Azure Web Server
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      
    defaults:
      run:
        working-directory: ${{ env.WEBAPP_DIRECTORY }}
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ env.ARM_CLIENT_ID }}
            tenant-id: ${{ env.ARM_TENANT_ID }}
            subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          terraform init -backend-config="state.backend.conf" -reconfigure

      - name: Terraform Plan
        run: |
          terraform plan -var-file="variables.tfvars" -out webapp.tfplan

      - name: Approve Terraform Apply
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: alejo-maya
          minimum-approvals: 1
          issue-title: "Deploying infra for the webapp to an azure web server"
          issue-body: "Please approve or deny the deployment."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: 'approve'
          additional-denied-words: 'reject'

      - name: Terraform Apply
        run: |
          terraform apply "webapp.tfplan"
